dist: trusty # container based ubuntu 14.4
sudo: false

language: java
jdk: 
  - oraclejdk8
script:
  - ./travis.sh
#  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install 
#  - mvn sonar:sonar
#  - mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar

notifications:
  email
    - hemantsonu20@gmail.com
addons:
  sonarqube:
    token:
      secure: $SONAR_GITHUB_TOKEN
  apt:
    packages:
      - google-chrome-stable
      
before_install:
  - chmod +x ./travis.sh

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3
